name: CD

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: version
        run: echo "::set-output name=version::$(date +"%-y.%-m.%-d")"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build-linux:
    needs: create-release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-linux
          path: loda
  build-macos:
    needs: create-release
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: version
        run: echo "::set-output name=version::$(date +"%-y.%-m.%-d")"
        id: version
      - name: test
        run: echo ${{ steps.version.outputs.version }}
      - name: Build
        run: cd src && make
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-macos
          path: loda
  build-windows:
    needs: create-release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: version
        run: echo "::set-output name=version::$(date +"%-y.%-m.%-d")"
        id: version
      - name: test
        run: echo "${{ steps.version.outputs.version }}"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: cd src && nmake.exe /F Makefile.windows
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-windows
          path: loda.exe
