name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: version
        run: date +"%y.%m.%d"
        id: version
      - name: test
        run: echo "${{ steps.version.outputs.version }}"
      - name: Build
        run: cd src && make
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-linux
          path: loda
  build-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: version
        run: date +"%y.%m.%d"
        id: version
      - name: test
        run: echo "${{ steps.version.outputs.version }}"
      - name: Build
        run: cd src && make
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-macos
          path: loda
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: version
        run: date +"%y.%m.%d"
        id: version
      - name: test
        run: echo "${{ steps.version.outputs.version }}"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: cd src && nmake.exe /F Makefile.windows
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: loda-windows
          path: loda.exe
