name: Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Version
        id: generate-version
        run: echo "::set-output name=version::$(date +"%-y.%-m.%-d")"
      - name: Create Release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.generate-version.outputs.version }}
          tag_name: v${{ steps.generate-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
      upload_url: ${{ steps.create-release.outputs.upload_url }}
  build-linux-x86:
    needs: create-release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make -f Makefile.linux-x86 loda LODA_PLATFORM=linux-x86 LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda
          asset_name: loda-linux-x86
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build-linux-arm64:
    needs: create-release
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cd src && make -f Makefile.linux-arm64 loda LODA_PLATFORM=linux-arm64 LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda
          asset_name: loda-linux-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build-macos:
    needs: create-release
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd src
          make -f Makefile.macos-x86 loda LODA_PLATFORM=macos LODA_VERSION=${{ needs.create-release.outputs.version }}
          mv loda loda-x86
          make clean
          make -f Makefile.macos-arm64 loda LODA_PLATFORM=macos LODA_VERSION=${{ needs.create-release.outputs.version }}
          mv loda loda-x86
          make clean
          lipo -create -output loda loda-x86 loda-arm64
          rm loda-x86 loda-arm64
          file loda
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda
          asset_name: loda-macos
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload (legacy macos-11)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda
          asset_name: loda-macos-11
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build-windows:
    needs: create-release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: cd src && nmake.exe /F Makefile.windows loda LODA_PLATFORM=windows LODA_VERSION=${{ needs.create-release.outputs.version }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda.exe
          asset_name: loda-windows.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload (legacy windows-19)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./loda.exe
          asset_name: loda-windows-19.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
